project:
  type: website
  output-dir: docs

website:
  title: "Abigail Krenz"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Data Viz
        menu: 
          - text: Inequality across countries
            href: TidyTuesday1.qmd
          - text: Race in obgyn studies
            href: TidyTuesday2.qmd
          - text: FLOTUS Tweets
            href: Project2.qmd
          - text: Gender Representation in the US Congress
            href: Project3.qmd
          - text: Ethical Dilemmas of Risk Assessment Tools
            href: Project4.qmd
          - text: Traffic Stops in Bay Area Cities
            href: Project5.qmd
          - text: Term Presentation
            href: Presentation.qmd

format:
  html:
    theme: jolla
    css: styles.css
    toc: true
    page-layout: full